export const services = [
  { name: "Cosmetic Dentistry", icon: "/Images/icons/Cosmetic dentistry.png", link: "/services/cosmetic-dentistry" },
  { name: "Crowns and Bridges", icon: "/Images/icons/dental-crown.png", link: "/services/crowns-and-bridges" },
  { name: "Dental Emergencies", icon: "/Images/icons/emergency denstiry.png", link: "/services/dental-emergencies" },
  { name: "Dental Implants", icon: "/Images/icons/implant.png", link: "/services/dental-implants" },
  { name: "Emergency Dentistry", icon: "/Images/icons/emergency denstiry.png", link: "/services/emergency-dentistry" },
  { name: "Fillings", icon: "/Images/icons/tooth-filling.png", link: "/services/fillings" },
  { name: "Invisalign", icon: "/Images/icons/Invisalign.png", link: "/services/invisalign" },
  { name: "Kids & Children Dentistry", icon: "/Images/icons/braces.png", link: "/services/kids-&-children-dentistry" },
  { name: "Oral Surgery", icon: "/Images/icons/oral surgery.png", link: "/services/oral-surgery" },
  { name: "Orthodontics", icon: "/Images/icons/orthodontics.png", link: "/services/orthodontics" },
  { name: "Permanent Teeth Replacement", icon: "/Images/icons/Teeth Replacement.png", link: "/services/permanent-teeth-replacement" },
  { name: "Root Canal", icon: "/Images/icons/root-canal.png", link: "/services/root-canal" },
  { name: "Sports Dentistry", icon: "/Images/icons/sports dentistry.png", link: "/services/sports-dentistry" },
  { name: "Tooth Extraction", icon: "/Images/icons/tooth-extraction.png", link: "/services/tooth-extraction" },
  { name: "Whitening & Veneers", icon: "/Images/icons/tooth-whitening.png", link: "/services/whitening-&-veneers" },
  { name: "Cosmetic Fillings", icon: "/Images/icons/tooth-filling.png", link: "/services/fillings" },
  { name: "Dental Checkup", icon: "/Images/icons/Dental checkup.png", link: "/services/dental-checkup" },
  { name: "Implant Restoration", icon: "/Images/icons/implant.png", link: "/services/implant-restoration" },
  { name: "Oral Cancer Screening", icon: "/Images/icons/oral surgery.png", link: "/services/oral-cancer-screening" },
  { name: "Preventive Dentistry", icon: "/Images/icons/emergency denstiry.png", link: "/services/preventive-dentistry" },
  { name: "Teeth Whitening", icon: "/Images/icons/tooth-whitening.png", link: "/services/whitening-&-veneers" },
]; 